server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: demo-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/whatsupclone_db?serverTimezone=Asia/Kolkata}
    username: ${SPRING_DATASOURCE_USERNAME:whatsup_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM:my-realm}/protocol/openid-connect/certs
  flyway:
    enabled: false

# Keycloak Configuration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:my-realm}
  resource: ${KEYCLOAK_RESOURCE:spring-backend}
  public-client: true
  bearer-only: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
    
application:
  file:
    upload:
      media-output:
        path: ./uploads

springdoc:
  default-produces-media-type: application/json

  
